name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  spm-build-test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build unit test target
      run: swift build
    - name: Run unit test target
      run: swift test
